### PR TITLE
fix issue #99: upgrade serialport and node-abi and bump version number

### PR DESCRIPTION
**Pull request by ReinoutHeeck**
This is my first ever pull request, please let me know if it is off the normal in some way.

## What does this implement/fix? Explain your changes.

fix compatibility issue with latest vscode:
-- bump the version number to 1.1.7
-- upgrade node-abi to 2.19.1
-- upgrade serialport to 9.0.1
-- download latest serialport binaries
-- ATTENTION: the new binaries I got only show 64-bit versions <-- NEEDS YOUR ATTENTION 

## Does this close any currently open issues?

yes: 
#99 Pymakr v1.1.6 doesn't work with VSC latest update 1.49.0

## Any relevant logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## Any other comments?
The download script only added 64-bit binaries, I don't know what I'm doing so this needs further attention.

## Where has this been tested?

**Operating system:**
Win 10 2004 build 19041.508

**VSCode version:**
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Pymakr version:**
I bumped this to 1.1.7

### CODE REVIEW

**Comment by jabelone** [comment]
Hey, I am experiencing issues with the plugin because vscode updated. It looks like this fixes the original issue, but introduces another one for me. I cloned your repository and built the extension from it, then installed it into vscode.

My Environment:
MacBook Pro
macOS 10.15.6

Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Here's the error if it's helpful:
```
[Extension Host] Error: Cannot find module './lib/main/settings-wrapper'
Require stack:
- /Users/jabelone/.vscode/extensions/pycom.pymakr-1.1.7/pymakr.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
	at Module._load (internal/modules/cjs/loader.js:737:27)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1046:268)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1015:981)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1012:303)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:135)
	at /Users/jabelone/.vscode/extensions/pycom.pymakr-1.1.7/pymakr.js:15:27
	at prepareSerialPort (/Users/jabelone/.vscode/extensions/pycom.pymakr-1.1.7/pymakr.js:149:9)
	at activate (/Users/jabelone/.vscode/extensions/pycom.pymakr-1.1.7/pymakr.js:7:5)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:917:841)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:917:492)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:915:724
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 5)
	at async Promise.all (index 0)
```

**Comment by ReinoutHeeck** [comment]
@jabelone that is strange, like your extension failed to install properly.
ls -l /Users/jabelone/.vscode/extensions/pycom.pymakr-1.1.7/lib/main/
should show 4 files, one of which is settings-wrapper.js

**Comment by ReinoutHeeck** [comment]
@jabelone I looked into this, it appears to be a problem with file permissions. 

Since I forked this project on MsWIndows it will fail to execute on Unix systems in the way you reported because execute bits get stripped from the .js files.

Unfortunately I don't have time to fix this today...

**Comment by elmasria** [comment]
Hi We have pushed a new version 1.1.7 which should solve your issue.
